language: python
python:
  - "3.4"
  - "3.5"
install:
  - "pip3 install pipenv"
  - "pipenv install flake8"
  - "pipenv install coveralls"
  - "pipenv install"
  - "pipenv lock"
  - "pipenv sync"
before_script:
  - "flake8"
script:
  - "nosetests --with-coverage --cover-package=gwrapper"
